# Generated by Django 2.2.24 on 2021-06-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contactNumber',
            field=models.IntegerField(),
        ),
    ]
