# Generated by Django 2.2.24 on 2021-06-14 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0002_auto_20210613_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('number_id', models.IntegerField()),
                ('issue_id', models.DateTimeField()),
                ('passport', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.IntegerField()),
                ('ocupation_date', models.DateTimeField()),
                ('leave_date', models.DateTimeField()),
                ('card_number', models.IntegerField()),
                ('card_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peopleCount', models.IntegerField()),
                ('period', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='serviceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='service',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='servicecompany',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Company'),
        ),
        migrations.AddField(
            model_name='servicecompany',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Service'),
        ),
        migrations.AddField(
            model_name='room',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Company'),
        ),
        migrations.AddField(
            model_name='reservationservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Service'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Company'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Customer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abode',
            name='Reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Reservation'),
        ),
        migrations.AddField(
            model_name='abode',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Room'),
        ),
    ]
