# Generated by Django 2.2.24 on 2021-06-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_auto_20210616_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='issue_id',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
