# Generated by Django 2.2.24 on 2021-06-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_auto_20210616_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Recepcionista', 'Recepcionista')], default='Recepcionista', max_length=20),
        ),
    ]
