# Generated by Django 2.2.24 on 2021-06-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_auto_20210617_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Ocupado', 'Ocupado')], default='Livre', max_length=10),
        ),
    ]
