# Generated by Django 2.2.24 on 2021-06-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_auto_20210617_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abode',
            name='room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluida', 'Concluida')], default='Pendente', max_length=20),
        ),
    ]
