# Generated by Django 2.2.24 on 2021-06-18 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_auto_20210617_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Company',
            new_name='company',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.Service'),
        ),
    ]
