# Generated by Django 2.2.24 on 2021-06-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0017_auto_20210618_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(limit_choices_to={'status': 'Livre'}, on_delete=django.db.models.deletion.CASCADE, to='adm.Room'),
        ),
    ]
