# Generated by Django 2.2.24 on 2021-06-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0018_auto_20210618_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
