# Generated by Django 2.2.24 on 2021-06-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0020_auto_20210618_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='status',
            field=models.CharField(choices=[('Concluida', 'Concluida'), ('Em andamento', 'Em andamento')], max_length=20),
        ),
    ]
