# Generated by Django 2.2.24 on 2021-06-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0021_auto_20210618_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='Reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluida', 'Concluida'), ('Em andamento', 'Em andamento'), ('Anulada', 'Anulada')], max_length=20),
        ),
    ]
