# Generated by Django 2.2.24 on 2021-06-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0024_auto_20210629_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
